# Generated by Django 3.2.6 on 2021-08-24 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 15, 4, 690313))),
                ('fecha_fin', models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 15, 4, 690313))),
                ('descriptcion', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, choices=[('c', 'Creado'), ('ep', 'En proceso'), ('ce', 'Cerrado')], default='c', max_length=15, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
