# Generated by Django 3.2.6 on 2021-08-24 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='descriptcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 36, 59, 608459)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 24, 9, 36, 59, 608459)),
        ),
    ]
